apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbsapp
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: kbsapp
  template:
    metadata:
      labels:
        app: kbsapp
    spec:
      containers:
      - name: kubernetes-test-app
        #image: kubernetes-test-app:latest
        #imagePullPolicy: Never  # Tell Kubernetes not to pull from a registry
        image: ankitarajdeep/kbsapp:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kbsapp
spec:
  selector:
    app: kbsapp
  ports:
  - port: 8080
    targetPort: 5000
